//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDMVisualization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GDMVisualization.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;graphml xmlns=&quot;http://graphml.graphdrawing.org/xmlns&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:y=&quot;http://www.yworks.com/xml/graphml&quot; xmlns:yed=&quot;http://www.yworks.com/xml/yed/3&quot; xsi:schemaLocation=&quot;http://graphml.graphdrawing.org/xmlns http://www.yworks.com/xml/schema/graphml/1.1/ygraphml.xsd&quot;&gt;
        ///  &lt;!--Created by yFiles for Java 2.8--&gt;
        ///  &lt;key for=&quot;graphml&quot; id=&quot;d0&quot; yfiles.type=&quot;resources&quot;/&gt;
        ///  &lt;key for=&quot;port&quot; id=&quot;d1&quot; yfiles.type=&quot;port [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExperimentGraph {
            get {
                return ResourceManager.GetString("ExperimentGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;  &lt;graphml xmlns=&quot;http://graphml.graphdrawing.org/xmlns&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:y=&quot;http://www.yworks.com/xml/graphml&quot; xmlns:yed=&quot;http://www.yworks.com/xml/yed/3&quot; xsi:schemaLocation=&quot;http://graphml.graphdrawing.org/xmlns http://www.yworks.com/xml/schema/graphml/1.1/ygraphml.xsd&quot;&gt;    &lt;!--Created by yFiles for Java 2.10--&gt;    &lt;key for=&quot;graphml&quot; id=&quot;d0&quot; yfiles.type=&quot;resources&quot;/&gt;    &lt;key for=&quot;port&quot; id=&quot;d1&quot; yfiles.type=&quot;por [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string graphHard {
            get {
                return ResourceManager.GetString("graphHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;graphml xmlns=&quot;http://graphml.graphdrawing.org/xmlns&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:y=&quot;http://www.yworks.com/xml/graphml&quot; xmlns:yed=&quot;http://www.yworks.com/xml/yed/3&quot; xsi:schemaLocation=&quot;http://graphml.graphdrawing.org/xmlns http://www.yworks.com/xml/schema/graphml/1.1/ygraphml.xsd&quot;&gt;
        ///  &lt;!--Created by yFiles for Java 2.8--&gt;
        ///  &lt;key for=&quot;graphml&quot; id=&quot;d0&quot; yfiles.type=&quot;resources&quot;/&gt;
        ///  &lt;key for=&quot;port&quot; id=&quot;d1&quot; yfiles.type=&quot;port [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tutorial {
            get {
                return ResourceManager.GetString("tutorial", resourceCulture);
            }
        }
    }
}
